name: CI

on:
  push:
    tags: [v*]
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs:
      - tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: git config --global url."https://${TOKEN}@github.com".insteadOf "https://github.com"
        continue-on-error: true

      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Setup google credentials
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
          credentials_file_path: /tmp/gcloud.json
        continue-on-error: true

      - name: Release
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  tests:
    name: Run tests
    #TODO: switch before merging
    uses: niedbalski/go-repo-template-1/.github/workflows/reusable-integration-tests.yml@reusable
    with:
      cloud_image_registry: ghcr.io
      cloud_image_name: ${{ github.repository }}/pr-3
      cloud_image_tag: latest
      target_repository: ${{ github.repository }}
      #TODO: switch before merging
      target_repository_ref: ${{ github.ref }}
      go_version: "1.17"
    secrets:
      fluentbit_config_validator_api_key: ${{ secrets.FLUENTBIT_CONFIG_VALIDATOR_API_KEY }}
      fluentd_config_validator_api_key: ${{ secrets.FLUENTD_CONFIG_VALIDATOR_API_KEY }}
      smtp_username: ${{ secrets.MAILTRAP_USERNAME }}
      smtp_password: ${{ secrets.MAILTRAP_PASSWORD }}
      image_registry_username: ${{ github.actor }}
      image_registry_password: ${{ secrets.PERSONAL_TOKEN }}