name: Integration tests
on:
  push:
    tags: [v*]
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  run-integration-cloud-api:
    name: run integration tests with cloud api
    uses: calyptia/go-repo-template/.github/workflows/reusable-run-integration-tests.yml@main
    with:
      cloud_image_name: niedbalski/cloud/pr-3
    secrets:
      fluentbit_config_validator_api_key: ${{ secrets.FLUENTBIT_CONFIG_VALIDATOR_API_KEY }}
      fluentd_config_validator_api_key: ${{ secrets.FLUENTD_CONFIG_VALIDATOR_API_KEY }}
      smtp_username: ${{ secrets.MAILTRAP_USERNAME }}
      smtp_password: ${{ secrets.MAILTRAP_PASSWORD }}
      registry_username: ${{ github.actor }}
      registry_password: ${{ secrets.PERSONAL_TOKEN }}
